apply plugin: 'com.android.library'

android {
    compileSdkVersion 29
    buildToolsVersion '28.0.3'

    lintOptions {
        abortOnError false
    }

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'androidx.annotation:annotation:1.0.0'
    compile 'com.scottyab:aescrypt:0.0.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'javax.inject:javax.inject:1'
    compile project(path: ':shoot-lib')
}